### ISSUE TITLE
(NOT AN ISSUE) Maybe we can join forces?

### ISSUE THREAD

**Issue by Tumppi066** [truckermudgeon/maps#14]
Hi! I'm contacting you here as you don't seem to have a lot of other socials.

I am the main developer of [ETS2LA](https://github.com/ETS2LA), an application for self driving in ETS2 and ATS.

We've gotten really far (to the point where we can do around 90% autonomous driving on V2), but especially the prefabs are still giving us issues.

Now I stumbled upon your map project and to be perfectly honest... **IT'S INCREDIBLE**.
 You've basically done what I've been struggling with for 2 years now!

I think there is a possibility here for us to combine our efforts to produce something incredible, you have the data and the map that we need, and we can provide you with a platform with a direct connection to ETS2 in addition to a whole lot of other features regarding self driving and route planning.

I am absolutely baffled on how extensive this program is, personally while trying to read data from ETS2 (especially prefabs) it's been taking considerable effort to get the data into a usable format.

If you think you can work with us in some capacity, then please do respond to me here or even better join the other devs @ https://discord.gg/ETS2LA

- Tumppi066, ETS2LA Dev Team

**Comment by truckermudgeon** [comment]
Hey @Tumppi066! I just watched [the video](https://www.youtube.com/watch?v=RAe3EcKyyBw)... what a cool project!

I'll be upfront: I'm very time-poor because of my day job. But maybe there's some small amount of help I can give to the ETS2LA project, even if it's just sharing knowledge or making changes to my `maps` project that would be helpful for you?

Can discuss more in your Discord 🙂

**Comment by Tumppi066** [comment]
We can talk more on Discord👍
